AllCops:
  Excludes:
    - db/seeds.rb
    - spec/fixtures/**

# 日本語でのコメントを許可する
AsciiComments:
  Enabled: false

# メソッドの戻り値としてブロックの値を使う場合にもエラーになるため無効
# にしている
Blocks:
  Enabled: false

Documentation:
  Enabled: false

# WindowsだとEndOfLine copが動作しないため無効にしている
EndOfLine:
  Enabled: false

# diffが少なくなるためハッシュや配列の最後のカンマは許可する
#TrailingComma:
#  Enabled: false

# デフォルトの10は短すぎる。80x25を基準として1画面に収まる長さとした。
MethodLength:
  Max: 25

# デフォルトの100は短すぎる。なんとなく250行とした。
ClassLength:
  Max: 250
