AllCops:
  Excludes:
    - db/seeds.rb
    - spec/fixtures/**

# 日本語でのコメントを許可する
AsciiComments:
  Enabled: false

# メソッドの戻り値としてブロックの値を使う場合にもエラーになるため無効
# にしている
Blocks:
  Enabled: false

Documentation:
  Enabled: false

# WindowsだとEndOfLine copが動作しないため無効にしている
EndOfLine:
  Enabled: false

# diffが少なくなるためハッシュや配列の最後のカンマは許可する
TrailingComma:
  Enabled: false
